apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }} 
data: 
  config.yaml: |
    api-key: 13yqd85lvgbdkdpqnrjf9arrep3pyy11yrmgsoxdg4r47mfy58cwudi9j6c9ol7y3acu3qhpnwkevma1t1kqmw8vbqjjbrq8zaj3iws
    satellite-addr: us-central-1.tardigrade.io 
    scope: 1BzwvcREnhzC7qsXwZFqhKCkX6bqs7uvNpgSciVYwwyTwhY69S6SR7D9G6phyoGtczBQ8uyZCDcZTthXpfiKQz3hBenNhr7qVvf16kS3CsWGAAZMe3gZMEs9rDvMN2D4XUeaW89oKSzdJKqWUMKHpymanNMFzAHK8fCQqimq78uDdzFfYFpN2KPvDY7pnJSSkK7SKhpZ
    minio.access-key: {{ .Values.accessKey }} 
    minio.secret-key: {{ .Values.secretKey }}
    server.address: :7777
