kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  accessKey: {{ .Values.accessKey }} 
  secretKey: {{ .Values.secretKey }}

